server:
  port: 9010

spring:
  application:
    name: "payment"
  config:
    import: "optional:configserver:http://localhost:8071/"

  datasource:
    url: "jdbc:oracle:thin:@//localhost:1521/ORCLPDB1"
    username: LESSONS
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          format_sql: true
    rabbitmq:
      host: "localhost"
      port: 5672
      username: "guest"
      password: "guest"
    flyway:
      enabled: "true"

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    root: INFO

  profiles:
    active: "dev"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"