server:
  port: 8080

spring:
  application:
    name: "students"
  datasource:
    url: "jdbc:oracle:thin:@//localhost:1521/ORCLPDB1"
    username: STUDENTS
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

  flyway:
    enabled: true

  cloud:
    openfeign:
      client:
        config:
          students:
            connectTimeout: 1500
            readTimeout: 6000

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/



logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [corr=%X{correlationId:-}] - %msg%n"
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"












