server:
  port: 8080

spring:
  application:
    name: students
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    username: MAX
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

